# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# shopt -s globstar

[ -f "${HOME}/.bashrc_local" ] && source "${HOME}/.bashrc_local"
return
