#!/usr/bin/env bash

after init interactive
after esc

function load()
{
  COLOUR_BLACK="${ESC}[30m";
  COLOUR_RED="${ESC}[31m";
  COLOUR_GREEN="${ESC}[32m";
  COLOUR_YELLOW="${ESC}[33m";
  COLOUR_BLUE="${ESC}[34m";
  COLOUR_CYAN="${ESC}[35m";
  COLOUR_MAGENTA="${ESC}[36m";
  COLOUR_WHITE="${ESC}[37m";
  COLOUR_HIGHLIGHT_BLACK="${ESC}[30;1m";
  COLOUR_HIGHLIGHT_RED="${ESC}[31;1m";
  COLOUR_HIGHLIGHT_GREEN="${ESC}[32;1m";
  COLOUR_HIGHLIGHT_YELLOW="${ESC}[33;1m";
  COLOUR_HIGHLIGHT_BLUE="${ESC}[34;1m";
  COLOUR_HIGHLIGHT_CYAN="${ESC}[35;1m";
  COLOUR_HIGHLIGHT_MAGENTA="${ESC}[36;1m";
  COLOUR_HIGHLIGHT_WHITE="${ESC}[37;1m";
  COLOUR_DEFAULT="${ESC}[0m";
}
